apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: operator-webhook-allow-traffic-api-server
  namespace: {{.Namespace}}
spec:
  podSelector:
    matchLabels:
      app: operator-webhook
  ingress:
  - ports:
    - protocol: TCP
      port: {{.OperatorWebhookNetworkPolicyPort}}
  egress:
  - ports:
    - protocol: TCP
      port: {{.OperatorWebhookNetworkPolicyPort}}
  policyTypes:
  - Ingress
  - Egress
