name: Fork CI

on:
  push:
    branches:
      - network-operator-*
    tags:
      - network-operator-*

jobs:
  call-reusable-ci-fork-workflow:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/fork-ci-reusable.yml@main
    with:
      registry-internal: nvcr.io/nvstaging/mellanox
      service-account-username: nvidia-ci-cd
      service-account-email: svc-cloud-orch-gh@nvidia.com
      components: '[{"name": "SriovNetworkOperator", "imageName": "sriov-network-operator", "Dockerfile": "Dockerfile.nvidia"},
            {"name": "SriovNetworkOperatorWebhook", "imageName": "sriov-network-operator-webhook", "Dockerfile": "Dockerfile.webhook.nvidia"},
            {"name": "SriovConfigDaemon", "imageName": "sriov-network-operator-config-daemon", "Dockerfile": "Dockerfile.sriov-network-config-daemon.nvidia"},
            {"name": "SriovConfigDaemonStig", "imageName": "sriov-network-operator-config-daemon-stig-fips", "Dockerfile": "Dockerfile.sriov-network-config-daemon-stig"}]'
      chart-name: sriov-network-operator
      chart-path: "deployment/sriov-network-operator-chart"
      exclude-chart-files: '["Chart.yaml"]'
    secrets:
      registry-username: ${{ secrets.NVCR_USERNAME }}
      registry-token: ${{ secrets.NVCR_TOKEN }}
      cicd-gh-token: ${{ secrets.GH_TOKEN_NVIDIA_CI_CD }}
      goproxy: ${{ secrets.GO_PROXY_URL }}
